"""linkedin

Revision ID: 22646d68f571
Revises: d384fdbd961a
Create Date: 2025-01-03 12:41:45.367151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22646d68f571'
down_revision: Union[str, None] = 'd384fdbd961a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('linkedin', sa.String(), nullable=True))
    op.drop_column('users', 'linkedln')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('linkedln', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'linkedin')
    # ### end Alembic commands ###
